Task/initial implementation
RebelCode/vc-repeater pull request #1
Opened 2017-12-19 16:17 UTC by romalytvynenko

Repeater implementation. Support extending render options (for root and for slot) in child.

2017-12-19 16:25 UTC, XedinUnknown requested changes

2017-12-19 16:25 UTC, XedinUnknown commented on src/index.js
> +            collectionItems () {
Maybe just `items`, since it's a property, and "the repeater's items" is quite intuitive?

2018-02-08 12:19 UTC, romalytvynenko commented
@XedinUnknown, I've already pushed fixes. Please, merge it.

2018-02-08 13:45 UTC, XedinUnknown approved these changes

2018-02-08 13:45 UTC, merged